### ISSUE TITLE
DocViewer UX

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-document-viewer-react#12]
## Phase 1 - Basic viewer research
 - [x] Interviews
 - [x] Personas
 - [x] Wireframing
 - [x] Testing
 - [x] Replanning
---- 
 - [x] Create resources
 - [x] Update desktop GUI
 - [x] Create mobile GUI
----
## Phase 2 - Basic editing
 - [x] Interviews - Prioritize the following editing functions - highlight, redaction, add text, modify text, digital signature
----
 - [x] Write blog post
